FROM python:{{ python_version }}-slim

WORKDIR /app

COPY pyproject.toml README.md ./
COPY src ./src

RUN pip install --no-cache-dir uv \
    && uv sync --no-dev

EXPOSE 8000

CMD ["uv", "run", "{{ package_name }}"]
